### ISSUE TITLE
build script fails with error `error[E0433]: failed to resolve: use of undeclared crate or module`

### ISSUE THREAD

**Issue by ManuelSopenaBallesteros** [Icelk/clap_autocomplete#4]
Dear clap autocomplete team,

I would like to use clap autocomplete but for some reason I get the following error:

```
error[E0433]: failed to resolve: use of undeclared crate or module `mesa`
 --> src/cli/build.rs:2:5
  |
2 | use mesa::hsm::hw_inventory::hw_component::types::ArtifactType;
  |     ^^^^ use of undeclared crate or module `mesa`

error[E0432]: unresolved import `strum`
 --> src/cli/build.rs:3:5
  |
3 | use strum::IntoEnumIterator;
  |     ^^^^^ use of undeclared crate or module `strum`
```

I am importing mesa and strum crates in my clap file. Not sure why it fails.

Any suggestion?

this is my build file https://github.com/eth-cscs/manta/blob/main/_build.rs
and this is my clap file building the cli https://github.com/eth-cscs/manta/blob/main/src/cli/build.rs

thank you very much for your help

**Comment by Icelk** [comment]
Hi!
This seems to be an issue with your build script. Including a different rust file via `include!` is bad practice and is what breaks your script. In the build script-environment, Cargo doesn't provice the dependencies for your normal project. So I'd suggest you split out the command generation into a different file. Maybe manually copying the file into the `_build.rs` would work too (since the `clap_autocomplete` dependency seems to be resolving), but I'm not sure.
